### ISSUE TITLE
missing package policycoreutils-python

### ISSUE THREAD

**Issue by wutzkachel** [ReinerNippes/nextcloud_on_docker#1]
After prepare_system.sh and ansible-playbook nextdocker.yml I get the following message:
-------------------------------------------------------------------------------------------------------------------------

TASK [prep_os : selinux targets] *********************************************************************************************************************
Wednesday 10 October 2018  16:03:39 -0400 (0:00:00.631)       0:01:35.899 ***** 
failed: [localhost] (item=/opt/nextcloud(/.*)?) => {"changed": false, "item": "/opt/nextcloud(/.*)?", "msg": "This module requires policycoreutils-python"}
After

yum install policycoreutils-python

everything worked quite well.

**Comment by ReinerNippes** [comment]
should be fixed.
https://github.com/ReinerNippes/nextcloud_on_docker/commit/59d5e20d697c9d1f450ebeb4caad1b7fa0647b59
