### ISSUE TITLE
Openning .odt/.ods/... files does not redirect to Collabora

### ISSUE THREAD

**Issue by xmiti** [ReinerNippes/nextcloud_on_docker#108]
Hello, first and foremost for a very nice piece code to help deploying NC :-)

I got stuck with Collabora.  When I try to open any OpenDoc file, e.g. odt or ods file, it ends up in NC Web "inside the original one".  See the following screenshot:
![Screenshot_2021-12-06_20-29-18](https://user-images.githubusercontent.com/47112870/144911539-edd4b1a5-7d68-4e11-bbe5-0da101e536b7.png)

The installation went fine with no issues, using the latest: 6fc9d8cd96f7ae8218d65ccb94caaf725b6ef928

I'm on `CentOS Linux release 8.5.2111`, `Docker version 20.10.11, build dea9396`.

I tried to search the logs and the only relevant thing I found is:
```
172.19.0.1 - - [06/Dec/2021:19:43:02 +0000] "GET /hosting/discovery HTTP/1.1" 200 34016 "-" "Nextcloud Server Crawler
" "172.19.0.1"
172.19.0.1 - - [06/Dec/2021:19:43:02 +0000] "GET /hosting/capabilities HTTP/1.1" 200 245 "-" "Nextcloud Server Crawle
r" "172.19.0.1"
 - - [06/Dec/2021:19:43:02 +0000] "GET /apps/richdocuments/index?fileId=21&requesttoken=f3MJG%2BrRRHEH
ljSWzA0LhInZoSrx5MamIFFIwOgEGK4%3D%3AUEM8Lo%2BCPRMwogL8uVtf1sey92mdsImXSQkli9lceuU%3D HTTP/1.1" 200 6535 "-" "Mozilla
/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
 - - [06/Dec/2021:19:43:02 +0000] "POST /browser/15dc78e/cool.html?WOPISrc=https%3A%2F%2F<SRVNAME>%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F21_occl3z9ol58i&title=Expense%20report.ods&la
ng=en&closebutton=1&revisionhistory=1 HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/201
00101 Firefox/95.0"
```

Could you please point me to the right direction where to look for?
BTW, have tried NC 23 and it didn't work too.

Thanks very much for any hint.

**Comment by ochealaaf** [comment]
I was lucky and found a solution for this problem yesterday. The fix is quick and easy. Edit the config file _nginx.conf_ and make 2 replacements. Search for _loleaflet_ and change it to _browser_, then look for _lool_ and replace it with _cool_. Save the file and restart your server. 
If you like to read the whole story please have a look here at the [Collabora Forum](https://forum.collaboraonline.com/t/upgrade-from-loolwsd-to-coolwsd-broke-nextcloud-use/742#!)

**Comment by xmiti** [comment]
Dear @ochealaaf, it works fine now. I was just blind.
Thank you very much, really appreciated.
