### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by github-cli** [ReinerNippes/nextcloud_on_docker#109]
Hi, just wondering but is there any way to afterwards simply use it with docker-compose files?
i mean it`d be nice if this would simply create Dockerfiles for mods and for the rest create a docker-compose.yml
that way small modifications could be done after...

**Comment by ReinerNippes** [comment]
You may try https://hub.docker.com/r/red5d/docker-autocompose/ to create docker-compose files from your setup. 
The other way to easily modify the container would be portainer.
