### ISSUE TITLE
ignores inventory + unable to get installed with sqlite

### ISSUE THREAD

**Issue by mod25** [ReinerNippes/nextcloud_on_docker#11]
hi,
is it correct that the install script ignore settings like data path, it still be as default /opt/nextcloud instead of /media/1TB/nextcloud. if i choose sqlite i get nextcloud-db doesn't exist i need to choose pgsql then it will install fine.
also traefik ist installed (which i didn't enabled). 
what i also don't understand it doesn't use nginx as proxy

pi@docker:~ $ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                      NAMES
e6402851e4dd        containrrr/watchtower:latest   "/watchtower --clean…"   38 hours ago        Up 38 hours                                                    watchtower
6dab02efcdbf        nginx:alpine                   "nginx -g 'daemon of…"   2 days ago          Up 2 days           80/tcp                                     nginx
ab6c7790eebf        nextcloud:fpm-alpine           "/entrypoint.sh php-…"   2 days ago          Up 2 days           9000/tcp                                   nextcloud
2a8a450f629d        redis:4-alpine                 "docker-entrypoint.s…"   2 days ago          Up 2 days           6379/tcp                                   redis
d708f9c8cfe9        postgres:10-alpine             "docker-entrypoint.s…"   2 days ago          Up 2 days           5432/tcp                                   nextcloud-db
831001df43c9        portainer/portainer:latest     "/portainer --host u…"   2 days ago          Up 2 days           9000/tcp                                   portainer
5248a92f55b2        traefik:alpine                 "/entrypoint.sh trae…"   2 days ago          Up 2 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik

my system i try to install on is raspbian on raspberry pi 3 b+

thank you for your support

**Comment by ReinerNippes** [comment]
traefik is the default proxy. it handle letsencrypt and selfsigned certificates out-of-the-box. this is not an option. nginx is just the web server for static web content incase you choose the fpm docker image.

the data path setting i'll have to check.

**Comment by ReinerNippes** [comment]
both issues should be fixed now.
