### ISSUE TITLE
Lower reserved memory ubuntu

### ISSUE THREAD

**Issue by LAazsx** [ReinerNippes/nextcloud_on_docker#113]
Hello,

Things are going well so far. One issue I'm having is that the VM where I've installed NC is reserving 16GB of RAM. I'm guessing this is by design in the playbook but is it possible to lower the reservation?

**Comment by ReinerNippes** [comment]
Memory reservation of a VM is not covered by the playbook. This is handled by your hypervisior. Or?

**Comment by LAazsx** [comment]
Oh, I assumed that the playbook did the memory reservation, because it shot up to 16gb after installing NC. My bad. Hypervisor is on automatic allocation. I'll set set it to a lower amount.

Thanks!
