### ISSUE TITLE
Apps: extract

### ISSUE THREAD

**Issue by hibryid** [ReinerNippes/nextcloud_on_docker#14]
Hello! Could You add supporting of extract app by default?
https://apps.nextcloud.com/apps/extract

![image](https://user-images.githubusercontent.com/32869232/65456798-cf699b00-de52-11e9-9db0-5aed373ee037.png)

**Comment by ReinerNippes** [comment]
i have changed the variable {{ nextcloud_app_config }} and added extract with state enable.

if you want additional apps just add them to the variable in file nextcloud_config/defaults/main.yml

https://github.com/ReinerNippes/nextcloud_on_docker/blob/3ab3d5ad5aef77654bf1eefdab7c4d53fd237490/roles/nextcloud_config/defaults/main.yml#L66
