### ISSUE TITLE
Nextcloud_config: first setup nextcloud

### ISSUE THREAD

**Issue by MishuMMx** [ReinerNippes/nextcloud_on_docker#15]
Hello

First i want to congratulate you on this project.

When i try to execute the ./nextdocker.yml i got:
<<<<<<<<<<<<<<<<<<
TASK [nextcloud_config : first setup nextcloud] **********************************************************************************************
Saturday 28 September 2019  09:09:34 -0400 (0:00:01.487)       0:02:13.144 **** 
fatal: [localhost]: FAILED! => changed=true 
  cmd: |-
    docker exec --user www-data nextcloud php occ  maintenance:install  --database mysql --database-host nextcloud-db --database-name nextcloud  --database-table-prefix oc_ --database-user nextcloud --database-pass FvIYw4cQaaMJ1aDqTlBKuuhZEMKbYbbe  --admin-user admin --admin-pass lgMFOVcKMzbZx7fedDMLD8jOl8DxA1R6 --data-dir /var/nc-data
  delta: '0:00:00.421351'
  end: '2019-09-28 09:09:34.756379'
  msg: non-zero return code
  rc: 1
  start: '2019-09-28 09:09:34.335028'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
     ->
  stdout_lines: <omitted>
PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=63   changed=22   unreachable=0    failed=1    skipped=20   rescued=0    ignored=0 
>>>>>>>>>>>>>>>>>>>>

All docker containers are up and running.
<<<<<<<<<<<<<<<<<<
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
8f9bb1bb35b9        nginx:alpine                             "nginx -g 'daemon of…"   6 minutes ago       Up 6 minutes        80/tcp                                     nginx
348f7054226f        nextcloud:fpm-alpine                     "/entrypoint.sh php-…"   6 minutes ago       Up 6 minutes        9000/tcp                                   nextcloud
6c1013357082        redis:4-alpine                           "docker-entrypoint.s…"   7 minutes ago       Up 6 minutes        6379/tcp                                   redis
b67a68befd22        mariadb:latest                           "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        3306/tcp                                   nextcloud-db
52fbe6e598ef        portainer/portainer:latest               "/portainer --host u…"   7 minutes ago       Up 7 minutes        9000/tcp                                   portainer
4fd889644f29        svendowideit/traefik-certdumper:latest   "/run.sh"                7 minutes ago       Up 7 minutes                                                   certdumper
aee0a6fa352c        traefik:1.7-alpine                       "/entrypoint.sh trae…"   7 minutes ago       Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik
4681983967bd        containrrr/watchtower:latest             "/watchtower --clean…"   7 minutes ago       Up 7 minutes                                                   watchtower
>>>>>>>>>>>>>>>>>>>>

So , i tried to run manually that docker command:
<<<<<<<<<<<<<<<<<<
root@debian:~/nextcloud_on_docker# docker exec -ti --user www-data nextcloud /bin/sh
/var/www/html $ php occ status
Nextcloud is not installed - only a limited number of commands are available
  - installed: false
  - version: 17.0.0.9
  - versionstring: 17.0.0
  - edition: 
/var/www/html $ php occ  maintenance:install  --database mysql --database-host nextcloud-db --database-name nextcloud  --database-table-prefix
 oc_ --database-user nextcloud --database-pass FvIYw4cQaaMJ1aDqTlBKuuhZEMKbYbbe  --admin-user admin --admin-pass lgMFOVcKMzbZx7fedDMLD8jOl8DxA
1R6 --data-dir /var/nc-data
Nextcloud was successfully installed
/var/www/html $
>>>>>>>>>>>>>>>>>>>>

Running again the  ./nextdocker.yml :
<<<<<<<<<<<<<<<<<<

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=68   changed=7    unreachable=0    failed=0    skipped=30   rescued=0    ignored=0
>>>>>>>>>>>>>>>>>>>>
:D success.

But, i don't know why it didn't succeed in the first run.

Please help me understand this .

Thank you

**Comment by ReinerNippes** [comment]
Up to now the playbook didn't wait for the database to come up.
I didn't notice this because normally I'm using the default database Postgresql and the database container is the first one to be created. So there was always a small delay before the first login from the nextcloud container. It seems that Postgresql is a bit quicker at startup.

Fixed it here: https://github.com/ReinerNippes/nextcloud_on_docker/blob/d4ca0bf7901e7826da2b49e3637bfe2a4cb25ed7/roles/docker_container/tasks/database.yml#L70

Please note that I also moved the location of the database files from /opt/nextcloud/database to a docker volume. On CentOS I run into permission problems with the old setup. 

If everything is up and running on your site you don't need to do anything. If you want start over better start with a fresh debian installation.

I'll soon merge the commit to master. Right now it's only in branch datavol.
