### ISSUE TITLE
curl command returns this python error

### ISSUE THREAD

**Issue by sunjam** [ReinerNippes/nextcloud_on_docker#18]
When executing:
`curl -s https://raw.githubusercontent.com/ReinerNippes/nextcloud_on_docker/master/prepare_system.sh | /bin/bash`

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-B4srK6/python-apt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-B4srK6/python-apt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-B4srK6/python-apt/pip-egg-info
         cwd: /tmp/pip-install-B4srK6/python-apt/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-B4srK6/python-apt/setup.py", line 6, in <module>
        from DistUtilsExtra.command import *
    ImportError: No module named DistUtilsExtra.command
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ReinerNippes** [comment]
you may try 
`https://raw.githubusercontent.com/ReinerNippes/nextcloud_on_docker/without_pip/prepare_system.sh`

on some distros the ansible package is rather old (ubuntu 18 -> ansible 2.5.x) so I used pip to install it plus additional packages. but a mixture of distro pip packages and `pip install ..` seems to a nightmare.

if the new script doesn't work as well, try to remove the pip packages installed by the old script.
