### ISSUE TITLE
Debian9: Error: Docker SDK for Python version is 1.9.0 (localhost''s Python /usr/bin/python). Minimum version required is 1.10.0

### ISSUE THREAD

**Issue by stephenmkbrady** [ReinerNippes/nextcloud_on_docker#21]
Hi, nice playbook, it's easy to use and understand for someone new-ish to ansible, I noticed a small issue for debian 9 install:
``` 
./nextcloud.yml
First install on debian 9:
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Error: Docker SDK for Python version is 1.9.0 (localhost''s Python /usr/bin/python). Minimum version required is 1.10.0.Use `pip install --upgrade docker-py` to upgrade. Hint: if you do not need Python 2.6 support, try `pip uninstall docker-py` instead, followed by `pip install docker`.'

```
Run:
`pip install --upgrade docker-py && ./nextcloud.yml`
It works.

**Comment by ReinerNippes** [comment]
that should be fixed.

https://github.com/ReinerNippes/nextcloud_on_docker/commit/d52d6bee1557c79cdd48676ceebb857903121d38

**Comment by james-cook** [comment]
I had this issue installing on Ubuntu 16.04 this afternoon so maybe there is a missing dependency check. 
In my case it could be down to **pip** not working during the install (in my case until OpenSSL directory was removed) - see: https://github.com/ReinerNippes/nextcloud_on_docker/issues/25
> pip install --upgrade docker-py
worked only after clearing the SSL problem

**Comment by stephenmkbrady** [comment]
Fixed for Debian, ran with a fresh install. 

> I had this issue installing on Ubuntu 16.04 this afternoon so maybe this is not quite fixed and there is a missing dependency check?
> In my case his problem could have been down to **pip** not working during the install (in my case until OpenSSL directory was removed) - see: #25
> 
> > pip install --upgrade docker-py
> 
> worked only after clearing the SSL problem

Sounds like the ubuntu issue was a side effect? 
I'll close this as title is debian and it's fixed for debian, and another can be open for the ubuntu as it's sounds like a different issue or at least different root cause.
