### ISSUE TITLE
Traefik dashboard enabled despite having "traefik_api_user" commented out

### ISSUE THREAD

**Issue by stephenmkbrady** [ReinerNippes/nextcloud_on_docker#23]
System Debian 9
```
# Uncomment 'traefik_api_user' to get access to your Traefik dashboard at https://nextcloud_server_fqdn/traefik .
# traefik_api_user          = traefik
```
I have `traefik_api_user` commented out but unfortunately the dashboard is visible.

**Comment by stephenmkbrady** [comment]
roles/docker_container/templates/traefik.toml.j2 has the following not wrapped with `{% if traefik_api_user is defined %}`
```
[api]
  entryPoint = "traefik"
  dashboard = false
```

**Comment by ReinerNippes** [comment]
thanks for your help.
it should be fixed with 
https://github.com/ReinerNippes/nextcloud_on_docker/commit/9d5eef6890799cad86a868381c9b1cb2ffcbfbfe

**Comment by stephenmkbrady** [comment]
Excellent, this can be closed
