### ISSUE TITLE
TURN server?

### ISSUE THREAD

**Issue by Spass1966** [ReinerNippes/nextcloud_on_docker#3]
Were you ever able to get a TURN server talking to Nextcloud for Talk?

**Comment by ReinerNippes** [comment]
sorry. not yet.
https://help.nextcloud.com/t/talk-turnserver-in-a-docker-container/49263
any idea?

**Comment by Spass1966** [comment]
No. :-( I saw your post on the forums and came over here to see if you had made any progress since so one replied to you.

I want to try putting a more up to date image of coturn based on this https://github.com/tolstoyevsky/mmb/blob/master/coturn/docker-compose.yml with this https://github.com/crazy-max/docker-nextcloud
and see if they can see each other.

**Comment by ReinerNippes** [comment]
did you try to install turn on the host? without docker?

**Comment by Spass1966** [comment]
No because I don't want to taint the state of my host OS. But I will report back to you if I get TURN working.

**Comment by ReinerNippes** [comment]
maybe tomorrow i'll try the turn container you used.

**Comment by Spass1966** [comment]
I wasn't able to get this working.

**Comment by ReinerNippes** [comment]
this config should work now.
https://github.com/ReinerNippes/nextcloud_on_docker/blob/f545c8ea74348d6af47643912ac95f3d3844338b/roles/docker_container/tasks/turnserver.yml#L32

(at least with a chrome browser.)

**Comment by Spass1966** [comment]
Got this to work with the following declaration in my `docker-compose.yml`:

 coturn:
    image: woahbase/alpine-coturn
    container_name: coturn
    tmpfs:
      - /var/lib/coturn
    volumes:
      - "./coturn/turnserver.conf:/var/lib/coturn/turnserver.conf"
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478"
    restart: always
```
```
