### ISSUE TITLE
Nginx and Traefik are deployed by default?

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#31]
Hi,

Maybe I don't understand it correctly, but it looks like Traefik and Nginx are both deployed in the default configuration.

Here contains the include_tasks for [Traefik](https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/tasks/main.yml#L13) and then here in the [groups_vars](https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/group_vars/all.yml#L19) the image is set to `fpm-alpine` and the [when statement](https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/tasks/main.yml#L37) checks if `fpm` is present which it always will be (unless changed)

This confuses me because I thought Traefik and Nginx are both reverse proxies. So why are they both deployed if they perform the same task?

Thanks.

**Comment by ReinerNippes** [comment]
nginx is both: web server and reverse proxy. but needs a side kick to get letsencrypt certificates.
traefik is a reverse proxy that handles automatically letsencrypt certificates. but it can't handle static html/css content.

**Comment by Dextroz** [comment]
I see that makes sense now. What if I just supply `nextcloud` as the nextcloud docker image? Does this image come with the apache web server? Does the playbook account for this?
