### ISSUE TITLE
Task failure: docker_container : wait for nextcloud-db to become ready

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#35]
```TASK [docker_container : wait for nextcloud-db to become ready] *************************************************************************************************************************************************Tuesday 04 February 2020  17:29:03 +0000 (0:00:00.583)       0:00:27.395 ******
fatal: [localhost]: FAILED! => changed=false
  elapsed: 31
  msg: Timeout when waiting for 172.21.0.3:3306
```

I just tried switching to mysql. Now having another issue... Looks like the DB doesn't come up quick enough?

**Comment by Dextroz** [comment]
Related to issues in #22

**Comment by Dextroz** [comment]
I believe this issue could be resolved by increasing the timeout duration? @ReinerNippes :-)

**Comment by ReinerNippes** [comment]
I just run the playbook on a AWS Ubuntu 18 EC2 and didn't encounter this problem.

What system are you using?

**Comment by Dextroz** [comment]
Ubuntu server 18.04 LTS.

**Comment by ReinerNippes** [comment]
do you run the playbook with a slow internet connection? 
on aws ec2s the initial download of any container image is just a snap. 

i increased the timeout to 600 sec.

https://github.com/ReinerNippes/nextcloud_on_docker/blob/082b75624674c06a8caa8bad5b46d04ead2a231f/roles/docker_container/tasks/database.yml#L81

**Comment by Dextroz** [comment]
I average around 90mbps.

**Comment by Dextroz** [comment]
Fix works.
