### ISSUE TITLE
Build Failed on SQL Container Setup: No manifest

### ISSUE THREAD

**Issue by ssd4130** [ReinerNippes/nextcloud_on_docker#4]
Description of Ansible playbook error:

TASK [docker_container : Create mysql container] *********************************************************************************************************************************************
Monday 29 April 2019  02:55:57 +0100 (0:00:00.906)       0:04:21.140 **********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling mariadb - code: None message: no matching manifest for unknown in the manifest list entries"}

**Comment by ReinerNippes** [comment]
Could be this docker issue? 

https://success.docker.com/article/error-pulling-image-no-matching-manifest

**Comment by ssd4130** [comment]
I tried installing JQ and that didn't solve the issue. I'm not sure what "unknown" is or where it's coming from (in the error message). I'm sure you saw that the manifest inspect command is only available for experimental versions of Docker. Is there a way the manifest can be avoided? I'd be happy to contribute to this project if it means being able to deploy on a Pi (I'm using a 3 B+)

**Comment by ReinerNippes** [comment]
raspi is still on my to do list.
what distro you are using? 
is docker working after you run the playbook?
