### ISSUE TITLE
Video and PDF thumbnail preview not working

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#41]
Hi,

It seems that videos and PDFs are not producing preview thumbnails.

Any idea how to solve this?

Thanks.

**Comment by ReinerNippes** [comment]
if that line 

https://github.com/ReinerNippes/nextcloud_on_docker/blob/082b75624674c06a8caa8bad5b46d04ead2a231f/roles/nextcloud_config/defaults/main.yml#L31

has no effect I'm afraid you may have to ask/search in the [forum](https://help.nextcloud.com). 

i think that would be a problem with the image.

**Comment by Dextroz** [comment]
Is it because the preview settings are to small?

**Comment by ReinerNippes** [comment]
I can test it tonight. 
If you have a test maschine: Edit the nextcloud_config/defaults/main.yml and rerun `nextdocker.yml -e force_nextcloud_config=true` or simply edit `/opt/nextcloud/config/config.ph`.

**Comment by Dextroz** [comment]
I’m not worried about generating these previews anymore. Closing.
