### ISSUE TITLE
Traefik cert dumper container

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#42]
Hello,

Does this container need to stay running once the setup is complete?

I think it may be causing issues as I keep having to accept the self-signed certificate in my browser, indicating that it is dumping a new cert?

Thanks.

**Comment by ReinerNippes** [comment]
The cert dumper should only export the traefik certs to /opt/nextcloud/traefik/certs|private so they can be used by other container which are not behind the traefik proxy (e.g. talk). 

The reason why you get new selfsigned certs might be a restart of the trafik container. But I'm not sure what causes traefik to generate a new cert.

**Comment by Dextroz** [comment]
The traefik dumper container seems to be in a constant restarting state. So I stopped it. This is ok? I don’t have talk or anything else deployed.

**Comment by ReinerNippes** [comment]
yes. that's ok. 
I'll check why it restart's. Is there something usefull in `docker logs certdumper`?

**Comment by Dextroz** [comment]
I'm using self-signed certs atm. Here are the logs from the container.
```
There was a problem parsing your acme.json file.

dumpcerts.sh <path to acme> <destination cert directory>
[Fri Feb 14 17:56:22 UTC 2020] Starting dumper into default mode
writing RSA key
jq: error (at /traefik/acme.json:15): Cannot iterate over null (null)

There was a problem parsing your acme.json file.

dumpcerts.sh <path to acme> <destination cert directory>
[Fri Feb 14 17:57:23 UTC 2020] Starting dumper into default mode
writing RSA key
jq: error (at /traefik/acme.json:15): Cannot iterate over null (null)

There was a problem parsing your acme.json file.

dumpcerts.sh <path to acme> <destination cert directory>
```

**Comment by Dextroz** [comment]
@ReinerNippes can I safely not use this container then if I don’t deploy talk?

**Comment by ReinerNippes** [comment]
yes. i think so.
