### ISSUE TITLE
Onlyoffice with apache image

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#44]
When using the latest apache image for nextcloud, the following error occurs `ONLYOFFICE cannot be reached. Please contact admin`.

How would I go about solving this?

**Comment by ReinerNippes** [comment]
You would have to follow this guide: https://helpcenter.onlyoffice.com/de/server/document/document-server-proxy.aspx and add the according labels to the onlyoffice container. So traefik would route the traffic to onlyoffice. Right now this is done by nginx.

**Comment by Dextroz** [comment]
Ok. So instead of: https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/templates/traefik.toml.j2#L29

Use the backend provided here?
https://github.com/ONLYOFFICE/document-server-proxy/blob/master/traefik/minimal.toml#L8

and provide the onlyoffice container with https://github.com/ONLYOFFICE/document-server-proxy/blob/master/tests/traefik/minimal/docker-compose.yaml#L10 ?

**Comment by ReinerNippes** [comment]
More or less. Yes.

In my setup traefik is configured with labels. So you have to "convert" the settings from the toml files to container labels. Examples here: https://github.com/ReinerNippes/nextcloud_on_docker/blob/00488c7b970bec55374d451d4afa96b7216d3700/roles/docker_container/tasks/nginx.yml#L35

If you don't have a extra domain you may look at the "proxy-to-virtual-path" config. 
https://github.com/ONLYOFFICE/document-server-proxy/blob/master/traefik/proxy-to-virtual-path.toml

And you have to adjust the nextcloud configuration: https://github.com/ReinerNippes/nextcloud_on_docker/blob/00488c7b970bec55374d451d4afa96b7216d3700/roles/nextcloud_config/tasks/configure_onlyoffice.yml#L16
