### ISSUE TITLE
Post deployment, nextcloud talk.

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#49]
Hello @ReinerNippes 

What steps would I need to take in order to enable Nextcloud talk for my instance where I originally didn't deploy Nextcloud talk and it's dependencies.

I realise the easiest thing to do would be to re-deploy but that's not an option for me currently.

Any steps/advice would be greatly appriciated. 😄

**Comment by ReinerNippes** [comment]
First: Make a Backup. 

Then the playbook should be idempotent. So you only have to edit the inventory file to enable talk installation and rerun the playbook.

But you should test the talk installation before on a second machine if you can. I had some trouble the time I wrote the playbook. And now there is a much newer version of talk.

**Comment by Dextroz** [comment]
So the playbook should see that the containers/files etc are already present and just continue?

**Comment by ReinerNippes** [comment]
Yes.

The most ansible modules always check before they change something. 

But some modules won't. E.g. the shell module is executed all the time. In this case you have to implement the idempotency yourself. 

So the task to initialize Nextcloud is only performed if the file config/config.php doesn't exist. You can see this in roles/configure_nextcloud/tasks/main.yml

I'm 95% sure that nothing would break. 

Nevertheless your system will be updated. That task will be triggered if newer OS packages are available.

So do a backup. ;-)

**Comment by Dextroz** [comment]
I am looking at the config for turn. Looks basically the same. Some slight differences but nothing major.
https://github.com/nextcloud/vm/blob/master/apps/talk.sh#L120

**Comment by ReinerNippes** [comment]
Here https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794 you'll find a how to configure everything.
