### ISSUE TITLE
Switching existing deployment from Onlyoffice -> Collabora.

### ISSUE THREAD

**Issue by Dextroz** [ReinerNippes/nextcloud_on_docker#50]
Hi 😄 

Recently, [Onlyoffice disabled mobile editing in the document server](https://github.com/ONLYOFFICE/DocumentServer/issues/805). In light of this. I am investigating how I can switch my existing installation from Onlyoffice to Collabora.

So far I have worked out:
1. Run `docker exec --user www-data nextcloud php occ app:disable onlyoffice`
2. I need to edit the nginx.conf. Remove the 2 aspects related to onlyoffice and add the 1 addition for collabora. Then restart the nginx container or reboot from within the container for the new config to take effect.
3. Remove `{{ nextcloud_www_dir }}/apps/onlyoffice` directory.
4. Remove the onlyoffice document server container.
5. Create the directory: `{{ nextcloud_www_dir }}/apps/richdocuments`.
6. Create the Collabora container as here: https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/tasks/collabora.yml
7. Run `docker exec --user www-data nextcloud php occ app:install/enable richdocuments`
8. Run `docker exec --user www-data nextcloud php occ config:app:set richdocuments wopi_url --value https://{{ nextcloud_server_fqdn }}:443`

Have I missed anything? 😄 

Thanks!

**Comment by ReinerNippes** [comment]
Again. Didn't test it too extensively. But you could simply run the playbook again after you changed the following line.

https://github.com/ReinerNippes/nextcloud_on_docker/blob/e61b42653f832c522203ff46102fcdbb32be131e/inventory#L68

`./nextdocker.yml -e "online_office=collabora"` should also work.

That wouldn't uninstall onlyoffice. This has to done manually as you described.
