### ISSUE TITLE
[Restic] backup_folder is in fact restic_repo ?

### ISSUE THREAD

**Issue by mdartic** [ReinerNippes/nextcloud_on_docker#51]
Hello, and thanks for your amazing work.

In the README and in the `inventory` file, you write :
```ini
# The restic backup tool will be installed when 'backup_folder' is not empty.
restic_repo                 = ''              # e.g. '/var/nc-backup' .
```
Is it in fact the `restic_repo` property ?

I can see in the `nextdocker.yml` file your following condition :
```
    - { role: prep_backup,       when: restic_repo != '' }
```

So I presume `backup_folder` is in fact `restic_repo` ?

If it's the case, I can make a PR if needed.

**Comment by ReinerNippes** [comment]
Thanks. 
You are right. I fixed this typo.
