### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by gonzogo** [ReinerNippes/nextcloud_on_docker#64]
Thanks to you Reiner I now have a working Nextcloud + Collabora instance.
After almost a week of failed attempts.
Even not knowing anything about Docker I'm very grateful for that 🙏🏼
Just one question: Is it possible to update to latest 19.x ?
If yes, how to proceed ? 
Thanks again!
Gonzo

**Comment by ReinerNippes** [comment]
If you didn't turn off auto update via watchtower: just sit and wait. 

search for the following lines:
https://github.com/ReinerNippes/nextcloud_on_docker/blob/6d3bca75516d670dd0b31a63c8e1de499b778b95/roles/docker_container/vars/main.yml#L28

each container with this label will be updated automatically. 

the images used are defined here:

https://github.com/ReinerNippes/nextcloud_on_docker/blob/6d3bca75516d670dd0b31a63c8e1de499b778b95/group_vars/all.yml#L18

if you don't want this progressive approach, change the values to your needs and rerun the playbook. 

so to stay on version 19 put `docker_nextcloud_image: 19-fpm-alpine` in `docker_container/vars/main.yml`

don't change the image family. don't change from `fpm-alpine` to `latest`. the playbook won't handle this for you.

if you want to stop auto update just stop or remove the watchtower container.

**Comment by gonzogo** [comment]
Hi Reiner,

I waited for a week but Nextcloud did not auto update yet.
I'm currently on 18.0.4 and  18.0.6 has been available since first install day. (And ideally I would like to use the latest 19 version).

On the web app admin settings page, the "Open updater" button bring a 404 page and the "Download now" button offers a zip download to my local machine.

The `com.centurylinklabs.watchtower.enable: "true"` label is present in all containers, I didn't turn off auto update via watchtower nor change anything from your install playbook.

The current nextcloud image is
`docker_nextcloud_image:        stable-fpm-alpine`
​
Where should I look to see if something's missing/wrong for auto updates to actually work?
​
Thanks again

<img width="665" alt="Screenshot 2020-06-21 at 10 26 01" src="https://user-images.githubusercontent.com/25160570/85221017-b3c6fd00-b3b0-11ea-9ee7-78e523d8163e.png">

**Comment by ReinerNippes** [comment]
I'm afraid everything is OK. stable-fpm-alpine is still on version 18.0.4 

https://hub.docker.com/layers/nextcloud/library/nextcloud/stable-fpm-alpine/images/sha256-7f1c2c3b9a4d76dcde3618115989979930a9ded5283f81b5fb4ac9775c310413?context=explore (Line 31)

![grafik](https://user-images.githubusercontent.com/15212916/85230454-88fc9900-b3f0-11ea-98dc-b0d1e234e72c.png)

If you want to update yourself have to choose another "fpm-alpine" image. Or have to wait for Nextcloud to update the stable-fpm-alpine image.

https://hub.docker.com/_/nextcloud?tab=tags&page=1&name=fpm-alpine

If you have a backup and tested the procedure on a test machine it should be save to change the image in group_vars/all.yml and rerun the playbook.

**Comment by gonzogo** [comment]
Thanks a lot Reiner, it's much clearer for me now!
