### ISSUE TITLE
Please consider add Linux Mint 20 support

### ISSUE THREAD

**Issue by nijisakai** [ReinerNippes/nextcloud_on_docker#73]
Thanks !

**Comment by ReinerNippes** [comment]
question: did you try the playbook on a Mint?

**Comment by nijisakai** [comment]
> question: did you try the playbook on a Mint?

Yes, i did try, and it failed.
Sorry i can't remember the exact error.

**Comment by ReinerNippes** [comment]
I use a lot distro dependent tasks and rely on the ansible fact variables:
https://github.com/ReinerNippes/nextcloud_on_docker/blob/d2b93016275ff3e4f321179a6833fef020d5a754/roles/prep_os/tasks/main.yml#L5
you may run https://github.com/ReinerNippes/ansible_var_dump on your Mint machine and look for the value of ansible_distribution  or ansible_distribution_release. 

if ansible_distribution is set to Mint there is no file Mint.yml in https://github.com/ReinerNippes/nextcloud_on_docker/tree/master/roles/prep_os/tasks and the playbook will fail.

1. just copy all Ubuntu.yml files to Mint.yml in all tasks folder where you find a Ubuntu.yml file. 
2. check if the additonal repos work for Mint. e.g.
https://github.com/ReinerNippes/nextcloud_on_docker/blob/d2b93016275ff3e4f321179a6833fef020d5a754/roles/prep_docker/tasks/Ubuntu.yml#L34

or you cold define the variables in the inventory and cheat
```
ansible_distribution = Ubuntu
```
I couldn't find a Mint image at AWS so I can't really test it.

**Comment by nijisakai** [comment]
> I use a lot distro dependent tasks and rely on the ansible fact variables:
> 
> https://github.com/ReinerNippes/nextcloud_on_docker/blob/d2b93016275ff3e4f321179a6833fef020d5a754/roles/prep_os/tasks/main.yml#L5
> 
> 
> you may run https://github.com/ReinerNippes/ansible_var_dump on your Mint machine and look for the value of ansible_distribution or ansible_distribution_release.
> if ansible_distribution is set to Mint there is no file Mint.yml in https://github.com/ReinerNippes/nextcloud_on_docker/tree/master/roles/prep_os/tasks and the playbook will fail.
> 
> 1. just copy all Ubuntu.yml files to Mint.yml in all tasks folder where you find a Ubuntu.yml file.
> 2. check if the additonal repos work for Mint. e.g.
>    https://github.com/ReinerNippes/nextcloud_on_docker/blob/d2b93016275ff3e4f321179a6833fef020d5a754/roles/prep_docker/tasks/Ubuntu.yml#L34
> 
> or you cold define the variables in the inventory and cheat
> 
> ```
> ansible_distribution = Ubuntu
> ```
> 
> I couldn't find a Mint image at AWS so I can't really test it.

Thank you! I will try it.
