### ISSUE TITLE
Fulltext search 

### ISSUE THREAD

**Issue by RST-J** [ReinerNippes/nextcloud_on_docker#77]
Thanks for this awesome playbook, I really appreciate the effort.  :+1: 

The only thing I have trouble with is the full text search feature - it doesn't install telling the version is not compatible with the version of the server. I didn't investigate it further yet, hoping this is an obvious one for you (to me it isn't, I am not familiar with ansible :grin:). And if it is that the app is not yet up to date for the latest Nextcloud version that would also be Ok and I know I cannot do anything about it.

Here the output for the attempt to install the fulltext search app:
```
failed: [localhost] (item=files_fulltextsearch_tesseract) => changed=true 
  ansible_loop_var: item
  cmd: docker exec --user www-data nextcloud php occ app:install files_fulltextsearch_tesseract
  delta: '0:00:01.273081'
  end: '2020-12-06 17:08:03.064780'
  item: files_fulltextsearch_tesseract
  msg: non-zero return code
  rc: 1
  start: '2020-12-06 17:08:01.791699'
  stderr: ''
  stderr_lines: <omitted>
  stdout: 'Error: App "Full text search - Files - Tesseract OCR" cannot be installed because it is not compatible with this version of the server.'
  stdout_lines: <omitted>
```

**Comment by ReinerNippes** [comment]
Fulltextsearch should be fixed now for NC20. 

https://github.com/ReinerNippes/nextcloud_on_docker/commit/2845f72ad89b4c399325fc7366de75047275fb59
