### ISSUE TITLE
Misdirected Request

### ISSUE THREAD

**Issue by ochealaaf** [ReinerNippes/nextcloud_on_docker#83]
Thanks a lot for this great ansible playbook. I am running several internet installations without problems.

For testing purposes in my private network I installed nextcloud_on_docker in a fresh VM based on Ubuntu 20.04 LTS. Installation procedure is completing without errors. As recommended I have chosen the local IP address of the VM as nextcloud_server_fqdn. 

Trying to connect to the nextcloud container via https://192.168.178.35 I get a white page saying 'Misdirected Request' instead of a nextcloud login prompt, same answer trying to connect the portainer container.   

I have checked the container log files (nginx , nextcloud, ...) but there are no error messages. Does anybody have a clue where to start debugging this issue?

**Comment by ReinerNippes** [comment]
I didn't test the new traefik setup with an IP adress instead of a fqdn. 
Nevertheless we start here: 
https://github.com/ReinerNippes/nextcloud_on_docker/blob/4bc38be0206dffe173a040f4c514c570f59f2522/roles/docker_container/tasks/nginx.yml#L36
That line attaches  a label to the nginx container to tell traefik to route any traffik according to this rules Host(\`192.168.178.100\`) to the nginx container.
Could you check with `docker inspect nginx` if that label is correct?

**Comment by ochealaaf** [comment]
It seems that the label is correct, output of docker inspect command contains this line:

 `"traefik.http.routers.nginx.rule": "Host(`192.168.178.35`)",`

**Comment by ReinerNippes** [comment]
Yes. That's correct.

And I just run the playbook with an IP address on an EC2 instance. It works. The IP is not the problem.

Anything in the traefik logs? `sudo docker logs traefik`

You can increase the log level here: 
https://github.com/ReinerNippes/nextcloud_on_docker/blob/4bc38be0206dffe173a040f4c514c570f59f2522/roles/docker_container/templates/traefik.yaml.j2#L32

I think `debug` will do.

or edit the file `/opt/nextcloud/traefik/traefik.yml` and restart traefik.

**Comment by ochealaaf** [comment]
My Firefox browser is presenting a TRAEFIK DEFAULT CERT, but I had a look at the traefik log file as you proposed 

```
time="2021-01-06T17:09:05Z" level=info msg="Configuration loaded from file: /traefik.yaml"
time="2021-01-06T17:09:25Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.178.35\": unable to generate a certificate for the domains [192.168.178.35]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"192.168.178.35\": The ACME server can not issue a certificate for an IP address, url: " providerName=certificatesResolverDefault.acme routerName=portainer@docker rule="Host(`192.168.178.35`) && PathPrefix(`/portainer/`)"
time="2021-01-06T17:10:57Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.178.35\": unable to generate a certificate for the domains [192.168.178.35]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"192.168.178.35\": The ACME server can not issue a certificate for an IP address, url: " routerName=portainer@docker rule="Host(`192.168.178.35`) && PathPrefix(`/portainer/`)" providerName=certificatesResolverDefault.acme
time="2021-01-06T17:14:34Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.178.35\": unable to generate a certificate for the domains [192.168.178.35]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"192.168.178.35\": The ACME server can not issue a certificate for an IP address, url: " routerName=portainer@docker rule="Host(`192.168.178.35`) && PathPrefix(`/portainer/`)" providerName=certificatesResolverDefault.acme
```
obviously trying to generate a letsencrypt certificate. BTW I did not provide an email address in the inventory.

**Comment by ochealaaf** [comment]
I have set up again a fresh Ubuntu virtual machine 20.04 with this playbook - same as described above - and there are no issues. 
I am wondering if a dynamic change of the IP address without noticing it might have caused this problem. Therefore I am closing this issue.
