### ISSUE TITLE
Details on upgrading when next version of nextcloud releases

### ISSUE THREAD

**Issue by sandy-rao** [ReinerNippes/nextcloud_on_docker#96]
I've successfully installed nextcloud on ubuntu 20.04 and everything seems great. I'm just not sure what the procedure to update nextcloud is in the future while retaining the existing data and databases.

Could you update the readme file with details. Thanks a lot.

**Comment by ReinerNippes** [comment]
I described it here https://github.com/ReinerNippes/nextcloud_on_docker/issues/75#issuecomment-731612887 
I'll put it in the readme soon. Promised.

**Comment by sandy-rao** [comment]
Thanks for the info. I see that it does auto-update. I have an issue with traefik generating new self-signed certificates randomly though. I'll open a separate issue for it. Thanks for the prompt reply.
