### ISSUE TITLE
traefik seems to generate new self-signed certificates after random intervals

### ISSUE THREAD

**Issue by sandy-rao** [ReinerNippes/nextcloud_on_docker#98]
I've successfully installed nextcloud on a local private ubuntu 20.04 server with self-signed certificate and everything seems great. I have been using it for the past month successfully but about every ~7 days (or maybe server restart) traefik seems to be generating a new self-signed certificate that prompts my nextcloud-client to prompt me to accept new self-signed certificate. I see that a self-signed certificate is valid for a year so the frequent new certificate generation is annoying.

Any ideas on how I can fix this issue. Could you point me towards a way to maybe manage my certificates manually so I can update them myself after a year if needed.

Thanks for the great script, really saved me a lot of hair-pulling.

**Comment by ReinerNippes** [comment]
i think after each restart a new self signed cert is generated. 
did you observe a new cert after a restart or update of the image?

**Comment by sandy-rao** [comment]
Yes, I think it definitely coincides with whenever I restart the server. I just restarted the server and got a new cert. Anyway of keeping the older cert which was still valid for close to a year?

**Comment by ReinerNippes** [comment]
Better ask in the traefik community. 
I always use Letsencrypt certs.
